version: '3.8'

services:
  daily_update:
    build:
      context: .
      dockerfile: daily_update/Dockerfile.daily_update
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - stock_network

networks:
  stock_network:
    external: true