version: '3.8'

services:
  daily_update:
    build:
      context: .
      dockerfile: daily_update/Dockerfile.daily_update
    volumes:
      - ./logs:/app/logs
      - ./StockDownloader:/app/StockDownloader
      - ./daily_update:/app/daily_update
    restart: unless-stopped
    networks:
      - stock_network

networks:
  stock_network:
    external: true